/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "login": [],
    "login.store": [],
    "logout": [],
    "password.confirm": [],
    "password.confirmation": [],
    "password.confirm.store": [],
    "two-factor.login": [],
    "two-factor.login.store": [],
    "two-factor.enable": [],
    "two-factor.confirm": [],
    "two-factor.disable": [],
    "two-factor.qr-code": [],
    "two-factor.secret-key": [],
    "two-factor.recovery-codes": [],
    "two-factor.regenerate-recovery-codes": [],
    "home": [],
    "dashboard": [],
    "sectores.index": [],
    "sectores.create": [],
    "sectores.store": [],
    "sectores.show": [
        {
            "name": "sectore",
            "required": true
        }
    ],
    "sectores.edit": [
        {
            "name": "sectore",
            "required": true
        }
    ],
    "sectores.update": [
        {
            "name": "sectore",
            "required": true
        }
    ],
    "sectores.destroy": [
        {
            "name": "sectore",
            "required": true
        }
    ],
    "sectores.ratios.index": [
        {
            "name": "sectore",
            "required": true
        }
    ],
    "sectores.ratios.create": [
        {
            "name": "sectore",
            "required": true
        }
    ],
    "sectores.ratios.store": [
        {
            "name": "sectore",
            "required": true
        }
    ],
    "ratios.show": [
        {
            "name": "ratio",
            "required": true
        }
    ],
    "ratios.edit": [
        {
            "name": "ratio",
            "required": true
        }
    ],
    "ratios.update": [
        {
            "name": "ratio",
            "required": true
        }
    ],
    "ratios.destroy": [
        {
            "name": "ratio",
            "required": true
        }
    ],
    "cuentas-base.index": [],
    "cuentas-base.create": [],
    "cuentas-base.store": [],
    "cuentas-base.show": [
        {
            "name": "cuentas_base",
            "required": true
        }
    ],
    "cuentas-base.edit": [
        {
            "name": "cuentas_base",
            "required": true
        }
    ],
    "cuentas-base.update": [
        {
            "name": "cuentas_base",
            "required": true
        }
    ],
    "cuentas-base.destroy": [
        {
            "name": "cuentas_base",
            "required": true
        }
    ],
    "plantillas-catalogo.index": [],
    "plantillas-catalogo.create": [],
    "plantillas-catalogo.store": [],
    "plantillas-catalogo.show": [
        {
            "name": "plantillas_catalogo",
            "required": true
        }
    ],
    "plantillas-catalogo.edit": [
        {
            "name": "plantillas_catalogo",
            "required": true
        }
    ],
    "plantillas-catalogo.update": [
        {
            "name": "plantillas_catalogo",
            "required": true
        }
    ],
    "plantillas-catalogo.destroy": [
        {
            "name": "plantillas_catalogo",
            "required": true
        }
    ],
    "empresas.index": [],
    "empresas.create": [],
    "empresas.store": [],
    "empresas.show": [
        {
            "name": "empresa",
            "required": true,
            "binding": "id"
        }
    ],
    "empresas.edit": [
        {
            "name": "empresa",
            "required": true,
            "binding": "id"
        }
    ],
    "empresas.update": [
        {
            "name": "empresa",
            "required": true,
            "binding": "id"
        }
    ],
    "empresas.destroy": [
        {
            "name": "empresa",
            "required": true,
            "binding": "id"
        }
    ],
    "empresas.catalogos.index": [
        {
            "name": "empresa",
            "required": true
        }
    ],
    "empresas.catalogos.create": [
        {
            "name": "empresa",
            "required": true
        }
    ],
    "empresas.catalogos.store": [
        {
            "name": "empresa",
            "required": true
        }
    ],
    "catalogos.show": [
        {
            "name": "catalogo",
            "required": true
        }
    ],
    "catalogos.edit": [
        {
            "name": "catalogo",
            "required": true
        }
    ],
    "catalogos.update": [
        {
            "name": "catalogo",
            "required": true
        }
    ],
    "catalogos.destroy": [
        {
            "name": "catalogo",
            "required": true
        }
    ],
    "empresas.estados-financieros.index": [
        {
            "name": "empresa",
            "required": true
        }
    ],
    "empresas.estados-financieros.create": [
        {
            "name": "empresa",
            "required": true
        }
    ],
    "empresas.estados-financieros.store": [
        {
            "name": "empresa",
            "required": true
        }
    ],
    "estados-financieros.show": [
        {
            "name": "estados_financiero",
            "required": true
        }
    ],
    "estados-financieros.edit": [
        {
            "name": "estados_financiero",
            "required": true
        }
    ],
    "estados-financieros.update": [
        {
            "name": "estados_financiero",
            "required": true
        }
    ],
    "estados-financieros.destroy": [
        {
            "name": "estados_financiero",
            "required": true
        }
    ],
    "analisis.ratios": [
        {
            "name": "empresa",
            "required": true
        },
        {
            "name": "anio",
            "required": true
        }
    ],
    "analisis.horizontal": [
        {
            "name": "empresa",
            "required": true
        }
    ],
    "analisis.historial-cuenta": [
        {
            "name": "empresa",
            "required": true
        }
    ],
    "empresas.proyecciones.index": [
        {
            "name": "empresa",
            "required": true
        }
    ],
    "empresas.proyecciones.create": [
        {
            "name": "empresa",
            "required": true
        }
    ],
    "empresas.proyecciones.store": [
        {
            "name": "empresa",
            "required": true
        }
    ],
    "proyecciones.show": [
        {
            "name": "proyeccione",
            "required": true
        }
    ],
    "proyecciones.edit": [
        {
            "name": "proyeccione",
            "required": true
        }
    ],
    "proyecciones.update": [
        {
            "name": "proyeccione",
            "required": true
        }
    ],
    "proyecciones.destroy": [
        {
            "name": "proyeccione",
            "required": true
        }
    ],
    "importacion.create": [],
    "importacion.store": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "password.edit": [],
    "password.update": [],
    "appearance.edit": [],
    "two-factor.show": [],
    "register": [],
    "register.store": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
